version: '2'

services:
  static-web:
    image: 'gustoase/landing:0.0.1'
    container_name: html
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'
